# neural_activity_simulation.py
# This script simulates basic neural activity and a simple thinking process in a higher intelligence model.
# It uses a simplified artificial neural network to demonstrate how neurons fire and propagate signals,
# mimicking decision-making or pattern recognition in a 'higher mind'.
# Author: Generated by Grok AI
# For GitHub: Create a repo, add this file, and include a README.md explaining the simulation.

import numpy as np
import matplotlib.pyplot as plt

class Neuron:
    def __init__(self, num_inputs, activation_function='sigmoid'):
        # Initialize weights randomly and bias
        self.weights = np.random.randn(num_inputs)
        self.bias = np.random.randn()
        self.activation_function = activation_function
    
    def activate(self, inputs):
        # Compute the weighted sum plus bias
        z = np.dot(self.weights, inputs) + self.bias
        if self.activation_function == 'sigmoid':
            return 1 / (1 + np.exp(-z))
        elif self.activation_function == 'relu':
            return max(0, z)
        else:
            raise ValueError("Unknown activation function")

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # Create layers: input to hidden, hidden to output
        self.hidden_layer = [Neuron(input_size) for _ in range(hidden_size)]
        self.output_layer = [Neuron(hidden_size) for _ in range(output_size)]
    
    def forward(self, inputs):
        # Propagate through hidden layer
        hidden_outputs = [neuron.activate(inputs) for neuron in self.hidden_layer]
        # Propagate to output layer
        outputs = [neuron.activate(hidden_outputs) for neuron in self.output_layer]
        return outputs
    
    def think(self, inputs):
        # Simulate 'thinking': forward pass and interpret output
        outputs = self.forward(inputs)
        decision = np.argmax(outputs)  # Simple decision based on max output
        return decision, outputs

def simulate_thinking_process():
    # Example: Simulate neural activity for a 'higher mind' deciding between options
    # Inputs could represent sensory data: e.g., [temperature, light, sound]
    inputs = np.array([0.5, 0.8, 0.2])  # Normalized inputs
    
    # Create a network: 3 inputs, 4 hidden neurons, 2 outputs (e.g., 'act' or 'rest')
    nn = NeuralNetwork(input_size=3, hidden_size=4, output_size=2)
    
    # Perform thinking
    decision, outputs = nn.think(inputs)
    print(f"Inputs: {inputs}")
    print(f"Neural outputs: {outputs}")
    print(f"Decision made: {'Act' if decision == 0 else 'Rest'}")
    
    # Visualize simple activity (firing rates)
    hidden_firings = [neuron.activate(inputs) for neuron in nn.hidden_layer]
    plt.bar(range(len(hidden_firings)), hidden_firings)
    plt.title("Hidden Neuron Firing Rates")
    plt.xlabel("Neuron Index")
    plt.ylabel("Activation")
    plt.show()

if __name__ == "__main__":
    simulate_thinking_process()
